# JWT
# Consist of 3 elements
# 1. Header
# What it contains:
# - Algorith used for signature (HS256)
# - Type of token (JWT)
headers = {"alg": "HS256", "typ": "JWT"}

# What happens:
# - Convert this JSON to string
# - Encode this string using base64url
# - Comes the result

# 2. Payload
# What it contains:
# User data (user_id, username, email e.t.c)
# Timestamp (issue at, expire at)
# Any custom information

# payload = {
#     'user_id': user.id,
#     'username': user.username,
#     'email': user.email,
#     'issue_at': datetime.utcnow(),
#     'expire_at': datetime.utcnow() + timedelta(days=7),
#     'custom_info': 'Some custom information'
# }
# What happens:
# - Convert this JSON to string
# - Encode this string using base64url
# - Comes the result
#
# 3. Signature
# - Cryptograhic seal that proves that the is genuine
# - Created using: Header + Payload + Secret Key
# - Secret Key: Random string generated by Django
#
# How it will made:
# Take the encoded header and payload
# Combine them with a dot: header.payload
# Use secret key (only server know this)
# Apply HMAC SHA256 Algorithm to create a hash.
# Encode the hash using base64url url encoding
#
# header.payload.signature


if __name__ == "__main__":
    # Header
    import base64
    import hashlib
    import hmac
    import json
    import time

    header = {"alg": "HS256", "typ": "JWT"}

    encoded_header = (
        base64.urlsafe_b64encode(json.dumps(header).encode("utf-8"))
        .decode("utf-8")
        .rstrip("=")
    )
    print(f"encoded_header: {encoded_header}")

    # Payload
    payload = {
        "user_id": 2,
        "username": "John Doe",
        "email": "john.doe@example.com",
        "issue_at": int(time.time()),
        "expire_at": int(time.time()) + 3600,  # 1hour
    }

    encoded_payload = (
        base64.urlsafe_b64encode(json.dumps(payload).encode("utf-8"))
        .decode("utf-8")
        .rstrip("=")
    )
    print(f"encoded_payload: {encoded_payload}")

    # Signature
    secret_key = "eg$*ctlc)i^4=-wd%59of!o@7#x8-(v56yzcu3ume3wnr+)n"
    message = f"{encoded_header}.{encoded_payload}"
    signature = hmac.new(secret_key.encode(), message.encode(), hashlib.sha256).digest()
    encoded_signature = base64.urlsafe_b64encode(signature).decode().rstrip("=")
    print(f"encoded_signature: {encoded_signature}")

    # JWT Token
    jwt_token = f"{encoded_header}.{encoded_payload}.{encoded_signature}"
    print(f"JWT Token: {jwt_token}")

    decoded_header = json.loads(
        base64.urlsafe_b64decode(encoded_header + "==").decode("utf-8")
    )
    print(f"decoded_header: {decoded_header}")

    decoded_payload = base64.urlsafe_b64decode(encoded_payload + "==").decode()
    print(f"decoded_payload: {decoded_payload}")

    decoded_signature = base64.urlsafe_b64decode(encoded_signature + "==").decode()
    print(f"decoded_signature: {decoded_signature}")


def login(request):
    if request.method == "POST":
        # 1. Get user credentials
        username = request.data.get("username")
        password = request.data.get("password")

        # 2. Authenticate user
        user = authenticate(username=username, password=password)

        if user is not None:
            # 3. Create JWT tokens
            refresh = RefreshToken.for_user(user)

        return Response(
            {
                "refresh": str(refresh),
                "access": str(refresh.access_token),
                "user_id": user.id,
                "user": user.username,
            }
        )

import jwt
def verify_jwt_token(token):
    payload = jwt.decode(token, secret_key, algorithms=["HS256"]
    return payload

def protected_view(request):
    auth_header = request.headers.get("Authorization", "")

    if not auth_header.startswith("Bearer "):
        return Response({"error": "Missing token"}, status=401)

    token = auth_header.split(" ")[1]
    payload = verify_jwt_token(token)
    print(f"payload: {payload}")
