# Generated by Django 4.1.7 on 2023-10-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=20)),
                ("password1", models.CharField(max_length=12)),
                ("password2", models.CharField(max_length=12)),
            ],
        ),
    ]
