# Generated by Django 4.1.7 on 2023-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("student_name", models.CharField(max_length=70)),
                ("student_email", models.EmailField(max_length=70)),
                ("student_password", models.CharField(max_length=70)),
                ("comment", models.CharField(default="not available", max_length=40)),
            ],
        ),
    ]
