# Generated by Django 4.1.7 on 2023-10-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_name", models.CharField(max_length=30)),
                ("faculty_id", models.IntegerField()),
                ("faculty_email", models.EmailField(max_length=254)),
                ("faculty_subjects", models.TextField()),
                ("faculty_slogan", models.TextField()),
            ],
        ),
    ]
