# Generated by Django 4.1.7 on 2023-10-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0002_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=30)),
                ("staff_id", models.IntegerField()),
                ("staff_email", models.EmailField(max_length=254)),
                ("staff_subjects", models.TextField()),
                ("staff_slogan", models.TextField()),
            ],
        ),
    ]
